from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Enum, Float, Text
from sqlalchemy.orm import relationship
from datetime import datetime
import enum

from app.database import Base


class OrderStatus(str, enum.Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class Order(Base):
    """Order table - stores core order information with analytics fields."""
    __tablename__ = "orders"

    id = Column(Integer, primary_key=True, index=True)
    order_number = Column(String(50), unique=True, nullable=False, index=True)
    customer_name = Column(String(255), nullable=False)
    customer_email = Column(String(255), nullable=True)
    product_name = Column(String(255), nullable=False)
    quantity = Column(Integer, nullable=False)
    priority = Column(String(20), default="normal")  # normal, high, urgent
    status = Column(Enum(OrderStatus), default=OrderStatus.PENDING, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    completed_at = Column(DateTime, nullable=True)

    # Lifecycle timestamps
    order_placed_at = Column(DateTime, nullable=True)
    order_confirmed_at = Column(DateTime, nullable=True)
    processing_completed_at = Column(DateTime, nullable=True)
    shipped_at = Column(DateTime, nullable=True)
    delivered_at = Column(DateTime, nullable=True)

    # Analytics fields - Stage durations (in hours)
    procurement_time = Column(Float, nullable=True, comment="Duration from order placed to confirmed (hours)")
    processing_time = Column(Float, nullable=True, comment="Duration from confirmed to processing completed (hours)")
    dispatch_time_duration = Column(Float, nullable=True, comment="Duration from processing completed to shipped (hours)")
    delivery_time_duration = Column(Float, nullable=True, comment="Duration from shipped to delivered (hours)")
    total_time = Column(Float, nullable=True, index=True, comment="Total lifecycle duration (hours)")

    # Analytics fields - SLA breach detection
    sla_breach = Column(Integer, default=0, nullable=False, index=True, comment="1 if SLA breached, 0 otherwise")
    breached_stage = Column(String(50), nullable=True, index=True, comment="Stage that breached SLA")

    # Analytics fields - Bottleneck detection
    bottleneck_stage = Column(String(50), nullable=True, index=True, comment="Stage identified as bottleneck")

    # Relationships
    stage_logs = relationship("StageLog", back_populates="order", cascade="all, delete-orphan")


class StageType(str, enum.Enum):
    ORDER_PLACED = "order_placed"
    ORDER_CONFIRMED = "order_confirmed"
    PROCESSING = "processing"
    QUALITY_CHECK = "quality_check"
    PACKAGING = "packaging"
    SHIPPED = "shipped"
    OUT_FOR_DELIVERY = "out_for_delivery"
    DELIVERED = "delivered"


class StageLog(Base):
    """StageLog table - tracks stage-wise progression of orders."""
    __tablename__ = "stage_logs"

    id = Column(Integer, primary_key=True, index=True)
    order_id = Column(Integer, ForeignKey("orders.id", ondelete="CASCADE"), nullable=False, index=True)
    stage_name = Column(Enum(StageType), nullable=False, index=True)
    stage_order = Column(Integer, nullable=False)  # Sequence number of the stage
    status = Column(String(50), default="pending", nullable=False)  # pending, in_progress, completed, failed
    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)
    duration_seconds = Column(Float, nullable=True)  # Time spent in this stage (seconds)
    notes = Column(Text, nullable=True)


# ── Demand Forecasting ─────────────────────────────────────────────────────────

class DemandRecord(Base):
    """Historical daily demand/sales data per product used for forecasting."""
    __tablename__ = "demand_records"

    id = Column(Integer, primary_key=True, index=True)
    product_id = Column(String(100), nullable=False, index=True)
    product_name = Column(String(255), nullable=False)
    category = Column(String(100), nullable=True, index=True)
    record_date = Column(DateTime, nullable=False, index=True)
    quantity_sold = Column(Float, nullable=False, comment="Units sold on this date")
    revenue = Column(Float, nullable=True, comment="Revenue generated on this date")
    inventory_level = Column(Float, nullable=True, comment="Stock level at end of day")
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class ForecastPrediction(Base):
    """Stored demand forecast predictions generated by the ML model."""
    __tablename__ = "forecast_predictions"

    id = Column(Integer, primary_key=True, index=True)
    product_id = Column(String(100), nullable=False, index=True)
    product_name = Column(String(255), nullable=True)
    forecast_date = Column(DateTime, nullable=False, index=True)
    predicted_demand = Column(Float, nullable=False)
    confidence_lower = Column(Float, nullable=True)
    confidence_upper = Column(Float, nullable=True)
    model_version = Column(String(50), nullable=True)
    horizon_days = Column(Integer, nullable=True, comment="Forecast horizon this row belongs to")
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    order = relationship("Order", back_populates="stage_logs")


class BottleneckAnalysis(Base):
    """BottleneckAnalysis table - stores identified bottlenecks."""
    __tablename__ = "bottleneck_analysis"

    id = Column(Integer, primary_key=True, index=True)
    order_id = Column(Integer, ForeignKey("orders.id", ondelete="CASCADE"), nullable=False, index=True)
    stage_name = Column(Enum(StageType), nullable=False)
    average_duration_seconds = Column(Float, nullable=True)
    threshold_seconds = Column(Float, nullable=False)
    actual_duration_seconds = Column(Float, nullable=True)
    is_bottleneck = Column(Integer, default=0)  # 0 = no, 1 = yes
    analysis_date = Column(DateTime, default=datetime.utcnow, nullable=False)
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)